server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml


management:
  server:
    port: 8081 #访问端口
  endpoints:
    web:
      base-path: /actuator/i #访问根目
      exposure:
        include: health,info           #web允许访问的路径